//! Ensure `web/map/dist/` exists at compile time for `RustEmbed`.
//!
//! The dist directory is gitignored and generated by `bun run build`. In dev
//! and `cargo install --path` workflows it exists on disk. When packaging
//! (`cargo package` / `cargo publish`), gitignored files are excluded from the
//! package archive, so the directory is absent and `#[derive(RustEmbed)]` fails.
//!
//! This build script creates a minimal fallback so the crate always compiles;
//! the nix flake grafts the real dist on top for the production binary.

use std::path::Path;

#[expect(clippy::disallowed_methods, reason = "build script — ephemeral stub for cargo package")]
fn main() {
    let dist = Path::new("web/map/dist");
    let index = dist.join("index.html");

    if !index.exists() {
        // dist/ missing — minimal stub so RustEmbed doesn't fail at compile time.
        let assets = dist.join("assets");
        let vendor = dist.join("vendor");

        std::fs::create_dir_all(&assets).ok();
        std::fs::create_dir_all(&vendor).ok();

        std::fs::write(
            &index,
            concat!(
                "<!DOCTYPE html>\n",
                "<html lang=\"en\"><head><meta charset=\"UTF-8\">",
                "<title>Doctrine Map Explorer</title></head>\n",
                "<body style=\"font-family:sans-serif;padding:2rem\">\n",
                "<h1>Frontend not built</h1>\n",
                "<p>Run <code>cd web/map &amp;&amp; bun run build</code> before ",
                "<code>cargo build --release</code>, or use the nix flake build.</p>\n",
                "</body></html>\n",
            ),
        )
        .ok();

        println!("cargo:warning=web/map/dist/ not found — using stub frontend");
    }

    // Re-run if the dist directory appears or changes.
    // In dev (dist present): re-builds when vite outputs change.
    // In packaging (dist absent): the path is recorded absent; no rerun.
    println!("cargo:rerun-if-changed=web/map/dist/index.html");
}
