//! SL-268 PHASE-01 — the behaviour-preservation golden for `doctrine review`.
//!
//! D4 (design.md sec-8) splits `src/review.rs` into an engine tier
//! (`review_ledger`) and a command tier (`review`) starting PHASE-02, and later
//! phases (IMP-029) change fail-safe reads, the turn journal, and more. This
//! file pins TODAY's CLI surface — stdout, stderr, exit code, and the authored
//! ledger TOML — byte-exact over the BUILT binary, so every later phase can
//! hold it green unchanged as the proof nothing behavioural moved along with
//! the code (RV-396 `F-7`).
//!
//! The only normalisation is the fixture root's string form → `<ROOT>`: it
//! covers `new`'s created directory and every path-bearing error. Nothing else
//! is carved out — a review ledger carries no dates/uids, `--color never` is
//! passed explicitly on every invocation so a stray `CLICOLOR_FORCE` cannot
//! inject ANSI, and the reservation degrade line is deterministic (no remote
//! configured from a bare tempdir).
//!
//! Expected strings are generated by running the built binary against each
//! fixture once and pasting the result — no bless/update env var exists in
//! this repo's `tests/e2e_*golden*.rs` family (A4), and inventing one here
//! would be new. A behaviour that looks like a bug is still pinned as-is; any
//! such oddity is called out in the phase notes, not carved out of the golden.

#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::tests_outside_test_module,
    reason = "integration test: fail-fast unwrap/expect are idiomatic, and test fns live at crate root by construction"
)]

use std::fs;
use std::path::Path;
use std::process::Output;

mod common;

// --- invocation + assertion helpers -----------------------------------------

/// `doctrine review <args...> -p <root> --color never` over the built binary —
/// the single invocation shape used by every test here, so a stray
/// `CLICOLOR_FORCE` cannot inject ANSI into a byte-exact assertion.
fn run(root: &Path, args: &[&str]) -> Output {
    common::doctrine_cmd(root)
        .arg("review")
        .args(args)
        .arg("-p")
        .arg(root)
        .arg("--color")
        .arg("never")
        .output()
        .expect("spawn doctrine")
}

fn stdout(out: &Output) -> String {
    String::from_utf8(out.stdout.clone()).expect("utf8 stdout")
}
fn stderr(out: &Output) -> String {
    String::from_utf8(out.stderr.clone()).expect("utf8 stderr")
}

fn tmp() -> tempfile::TempDir {
    tempfile::tempdir().expect("tempdir")
}

/// The write-path skip (ISS-260, mirrored from `e2e_adr_cli_golden.rs`): a
/// guard-`Write` review verb (new/raise/dispose/verify/contest/withdraw/
/// conclude/unlock — `src/commands/guard.rs:112-125`) is CORRECTLY
/// guard-refused inside a marked worker fork, so its golden's write/no-write
/// assertions no longer hold there — not a regression, just the wrong place to
/// run it. `list`/`show`/`status`/`prime`/`paths` are guard-`Read` and never
/// skip (A2). The coord-tree unmarked run is authoritative (VA-1).
fn skip_under_worker_marker(test_name: &str) -> bool {
    if common::under_worker_marker() {
        eprintln!("{test_name}: worker fork — skipping (authored write, guard-refused by design)");
        true
    } else {
        false
    }
}

/// Replace the fixture root's string form with `<ROOT>` — the ONLY
/// normalisation (EX-3). Tries `canonicalize()`'s display form first, then
/// `root.display()`, in case a symlinked tmp makes the two differ (both are
/// "the fixture root"). Applied to stdout/stderr only — ledger bytes carry no
/// root path and are compared raw.
fn norm(root: &Path, s: &str) -> String {
    let mut out = s.to_owned();
    if let Ok(canon) = root.canonicalize() {
        out = out.replace(&canon.display().to_string(), "<ROOT>");
    }
    out.replace(&root.display().to_string(), "<ROOT>")
}

/// Hand-seed one review's authored ledger + brief.
fn seed_review(root: &Path, id: u32, toml: &str, md: &str) {
    let dir = root.join(format!(".doctrine/review/{id:03}"));
    fs::create_dir_all(&dir).unwrap();
    fs::write(dir.join(format!("review-{id:03}.toml")), toml).unwrap();
    fs::write(dir.join(format!("review-{id:03}.md")), md).unwrap();
}

/// Hand-seed a minimal slice target — mirrors `src/review.rs`'s in-file
/// `plant_slice_with_selectors` fixture (design D9's path-set shape). Every
/// selector rides `intent = "design-target"` (`prime` unions all intents).
/// Enough for `ensure_ref_resolves` (a dir probe) and `slice::selector_paths`
/// (which reads the toml + md).
fn seed_slice(root: &Path, id: u32, selectors: &[&str]) {
    let dir = root.join(format!(".doctrine/slice/{id:03}"));
    fs::create_dir_all(&dir).unwrap();
    let mut toml = format!(
        "id = {id}\nslug = \"t\"\ntitle = \"T\"\nstatus = \"proposed\"\ncreated = \"2026-01-01\"\nupdated = \"2026-01-01\"\n"
    );
    for sel in selectors {
        toml.push_str(&format!(
            "\n[[selector]]\nselector = \"{sel}\"\nintent = \"design-target\"\n"
        ));
    }
    fs::write(dir.join(format!("slice-{id:03}.toml")), toml).unwrap();
    fs::write(dir.join(format!("slice-{id:03}.md")), "## Scope\n").unwrap();
}

/// Hand-seed a minimal ADR target (for the "target is not a slice" prime
/// refusal fixture) — just enough for `ensure_ref_resolves`.
fn seed_adr(root: &Path, id: u32) {
    let dir = root.join(format!(".doctrine/adr/{id:03}"));
    fs::create_dir_all(&dir).unwrap();
    let toml = format!(
        "id = {id}\nslug = \"a\"\ntitle = \"A\"\nstatus = \"accepted\"\ncreated = \"2026-01-01\"\nupdated = \"2026-01-01\"\ntags = []\n[relationships]\nsupersedes = []\nsuperseded_by = []\nrelated = []\n"
    );
    fs::write(dir.join(format!("adr-{id:03}.toml")), toml).unwrap();
    fs::write(dir.join(format!("adr-{id:03}.md")), "# ADR\n").unwrap();
}

/// Hand-seed a stale lock (S14/T10) — the `pid`/`acquired` diagnostic body
/// `LockGuard::acquire` writes (`src/review.rs:2371-2373`).
fn seed_lock(root: &Path, id: u32, body: &str) {
    let dir = root.join(format!(".doctrine/state/review/{id:03}"));
    fs::create_dir_all(&dir).unwrap();
    fs::write(dir.join("lock"), body).unwrap();
}

/// Read back one review's authored ledger bytes.
fn ledger(root: &Path, id: u32) -> String {
    fs::read_to_string(root.join(format!(".doctrine/review/{id:03}/review-{id:03}.toml"))).unwrap()
}

/// A minimal single-finding ledger at review id 1, target `SL-001`, default
/// raiser/responder labels — the shared base for the role/state refusal
/// fixtures (only the finding's `status` varies).
fn seed_one_finding(root: &Path, status: &str) {
    let toml = format!(
        "id    = 1\nslug  = \"t\"\ntitle = \"T\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-001\"\n\n[[finding]]\nid = \"F-1\"\nstatus = \"{status}\"\nseverity = \"blocker\"\ntitle = \"T1\"\ndetail = \"D1\"\n"
    );
    seed_review(root, 1, &toml, "# brief\n");
}

// --- ledger fixtures (exact bytes copied from the built binary, A4) ---------

/// `review new --facet design --target SL-001` — no phase, default
/// raiser/responder. The write-chain's starting point (T3).
fn fresh_ledger() -> &'static str {
    r#"id    = 1
slug  = "design-review-of-sl-001"
title = "design review of SL-001"
# no status — a review's status is DERIVED from its findings, so
# it is never stored (the storage rule forbids derived data in authored files).

[review]
facet     = "design"     # scope|design|plan|phase-plan|implementation|code-review|reconciliation
raiser    = "raiser"
responder = "responder"

[target]                   # the outbound `reviews` edge: RV-NNN ──reviews──▶ <ref>
ref   = "SL-001"

# Findings are append-only `[[finding]]` tables, added by `review raise`.
# Empty here at creation — a fresh review is Active, awaiting the raiser.
"#
}

/// `review new --facet design --target SL-001 --phase PHASE-01 --title "My T"
/// --raiser codex --responder claude` — the `[target].phase` line lands with
/// NO blank line before the trailing `# Findings` comment (template quirk,
/// pinned deliberately).
fn fresh_ledger_with_phase_and_labels() -> &'static str {
    r#"id    = 1
slug  = "my-t"
title = "My T"
# no status — a review's status is DERIVED from its findings, so
# it is never stored (the storage rule forbids derived data in authored files).

[review]
facet     = "design"     # scope|design|plan|phase-plan|implementation|code-review|reconciliation
raiser    = "codex"
responder = "claude"

[target]                   # the outbound `reviews` edge: RV-NNN ──reviews──▶ <ref>
ref   = "SL-001"
phase = "PHASE-01"
# Findings are append-only `[[finding]]` tables, added by `review raise`.
# Empty here at creation — a fresh review is Active, awaiting the raiser.
"#
}

/// `review-NNN.md` — identical for both `new` fixtures above (the brief
/// template splices only `{{ref}}`/`{{facet}}`/`{{target}}`, none of which
/// differ between S1 and S2).
fn fresh_brief() -> &'static str {
    r#"# Review RV-001 — design of SL-001

Adversarial-review ledger. Structured findings live in the sister
ledger toml; this prose companion carries the reviewer's framing.

## Brief

<!-- Pre-reading + lines of attack: what this review is probing, the invariants
     it must hold the subject to, and where the bodies are likely buried. Seeded
     at `review new`; the reviewer fills it before raising findings. -->
"#
}

/// Write-chain step 1: `raise F-1 blocker T1/D1`.
fn chain_step1_raise_f1() -> &'static str {
    r#"id    = 1
slug  = "design-review-of-sl-001"
title = "design review of SL-001"
# no status — a review's status is DERIVED from its findings, so
# it is never stored (the storage rule forbids derived data in authored files).

[review]
facet     = "design"     # scope|design|plan|phase-plan|implementation|code-review|reconciliation
raiser    = "raiser"
responder = "responder"

[target]                   # the outbound `reviews` edge: RV-NNN ──reviews──▶ <ref>
ref   = "SL-001"

[[finding]]
id = "F-1"
status = "open"
severity = "blocker"
title = "T1"
detail = "D1"

# Findings are append-only `[[finding]]` tables, added by `review raise`.
# Empty here at creation — a fresh review is Active, awaiting the raiser.
"#
}

/// Step 2: `raise F-2 major T2/D2`.
fn chain_step2_raise_f2() -> &'static str {
    r#"id    = 1
slug  = "design-review-of-sl-001"
title = "design review of SL-001"
# no status — a review's status is DERIVED from its findings, so
# it is never stored (the storage rule forbids derived data in authored files).

[review]
facet     = "design"     # scope|design|plan|phase-plan|implementation|code-review|reconciliation
raiser    = "raiser"
responder = "responder"

[target]                   # the outbound `reviews` edge: RV-NNN ──reviews──▶ <ref>
ref   = "SL-001"

[[finding]]
id = "F-1"
status = "open"
severity = "blocker"
title = "T1"
detail = "D1"

[[finding]]
id = "F-2"
status = "open"
severity = "major"
title = "T2"
detail = "D2"

# Findings are append-only `[[finding]]` tables, added by `review raise`.
# Empty here at creation — a fresh review is Active, awaiting the raiser.
"#
}

/// Step 3 (and, byte-identically, step 5): `dispose F-1 fixed/R1` from `open`.
fn chain_step3_dispose_f1() -> &'static str {
    r#"id    = 1
slug  = "design-review-of-sl-001"
title = "design review of SL-001"
# no status — a review's status is DERIVED from its findings, so
# it is never stored (the storage rule forbids derived data in authored files).

[review]
facet     = "design"     # scope|design|plan|phase-plan|implementation|code-review|reconciliation
raiser    = "raiser"
responder = "responder"

[target]                   # the outbound `reviews` edge: RV-NNN ──reviews──▶ <ref>
ref   = "SL-001"

[[finding]]
id = "F-1"
status = "answered"
severity = "blocker"
title = "T1"
detail = "D1"
disposition = "fixed"
response = "R1"

[[finding]]
id = "F-2"
status = "open"
severity = "major"
title = "T2"
detail = "D2"

# Findings are append-only `[[finding]]` tables, added by `review raise`.
# Empty here at creation — a fresh review is Active, awaiting the raiser.
"#
}

/// Step 4: `contest F-1 --note "not really"` — the note is baton-only (D10);
/// the ledger carries no trace of it, only the status flip.
fn chain_step4_contest_f1() -> &'static str {
    r#"id    = 1
slug  = "design-review-of-sl-001"
title = "design review of SL-001"
# no status — a review's status is DERIVED from its findings, so
# it is never stored (the storage rule forbids derived data in authored files).

[review]
facet     = "design"     # scope|design|plan|phase-plan|implementation|code-review|reconciliation
raiser    = "raiser"
responder = "responder"

[target]                   # the outbound `reviews` edge: RV-NNN ──reviews──▶ <ref>
ref   = "SL-001"

[[finding]]
id = "F-1"
status = "contested"
severity = "blocker"
title = "T1"
detail = "D1"
disposition = "fixed"
response = "R1"

[[finding]]
id = "F-2"
status = "open"
severity = "major"
title = "T2"
detail = "D2"

# Findings are append-only `[[finding]]` tables, added by `review raise`.
# Empty here at creation — a fresh review is Active, awaiting the raiser.
"#
}

/// Step 6: `verify F-1 --note ok`, from `answered` (the second dispose,
/// byte-identical to step 3, is skipped as a fixture — same string).
fn chain_step6_verify_f1() -> &'static str {
    r#"id    = 1
slug  = "design-review-of-sl-001"
title = "design review of SL-001"
# no status — a review's status is DERIVED from its findings, so
# it is never stored (the storage rule forbids derived data in authored files).

[review]
facet     = "design"     # scope|design|plan|phase-plan|implementation|code-review|reconciliation
raiser    = "raiser"
responder = "responder"

[target]                   # the outbound `reviews` edge: RV-NNN ──reviews──▶ <ref>
ref   = "SL-001"

[[finding]]
id = "F-1"
status = "verified"
severity = "blocker"
title = "T1"
detail = "D1"
disposition = "fixed"
response = "R1"

[[finding]]
id = "F-2"
status = "open"
severity = "major"
title = "T2"
detail = "D2"

# Findings are append-only `[[finding]]` tables, added by `review raise`.
# Empty here at creation — a fresh review is Active, awaiting the raiser.
"#
}

/// Step 7: `withdraw F-2`, from `open`.
fn chain_step7_withdraw_f2() -> &'static str {
    r#"id    = 1
slug  = "design-review-of-sl-001"
title = "design review of SL-001"
# no status — a review's status is DERIVED from its findings, so
# it is never stored (the storage rule forbids derived data in authored files).

[review]
facet     = "design"     # scope|design|plan|phase-plan|implementation|code-review|reconciliation
raiser    = "raiser"
responder = "responder"

[target]                   # the outbound `reviews` edge: RV-NNN ──reviews──▶ <ref>
ref   = "SL-001"

[[finding]]
id = "F-1"
status = "verified"
severity = "blocker"
title = "T1"
detail = "D1"
disposition = "fixed"
response = "R1"

[[finding]]
id = "F-2"
status = "withdrawn"
severity = "major"
title = "T2"
detail = "D2"

# Findings are append-only `[[finding]]` tables, added by `review raise`.
# Empty here at creation — a fresh review is Active, awaiting the raiser.
"#
}

/// Step 8 (and, byte-identically, the idempotent step-9 re-conclude):
/// `conclude` sets `concluded = true` under `[review]`.
fn chain_step8_conclude() -> &'static str {
    r#"id    = 1
slug  = "design-review-of-sl-001"
title = "design review of SL-001"
# no status — a review's status is DERIVED from its findings, so
# it is never stored (the storage rule forbids derived data in authored files).

[review]
facet     = "design"     # scope|design|plan|phase-plan|implementation|code-review|reconciliation
raiser    = "raiser"
responder = "responder"
concluded = true

[target]                   # the outbound `reviews` edge: RV-NNN ──reviews──▶ <ref>
ref   = "SL-001"

[[finding]]
id = "F-1"
status = "verified"
severity = "blocker"
title = "T1"
detail = "D1"
disposition = "fixed"
response = "R1"

[[finding]]
id = "F-2"
status = "withdrawn"
severity = "major"
title = "T2"
detail = "D2"

# Findings are append-only `[[finding]]` tables, added by `review raise`.
# Empty here at creation — a fresh review is Active, awaiting the raiser.
"#
}

/// Step 10 (S9): `raise F-3` on an already-`concluded` ledger succeeds and
/// `concluded` stays `true` (D2 flips this later — today's behaviour pinned
/// as-is).
fn chain_step10_raise_on_concluded() -> &'static str {
    r#"id    = 1
slug  = "design-review-of-sl-001"
title = "design review of SL-001"
# no status — a review's status is DERIVED from its findings, so
# it is never stored (the storage rule forbids derived data in authored files).

[review]
facet     = "design"     # scope|design|plan|phase-plan|implementation|code-review|reconciliation
raiser    = "raiser"
responder = "responder"
concluded = true

[target]                   # the outbound `reviews` edge: RV-NNN ──reviews──▶ <ref>
ref   = "SL-001"

[[finding]]
id = "F-1"
status = "verified"
severity = "blocker"
title = "T1"
detail = "D1"
disposition = "fixed"
response = "R1"

[[finding]]
id = "F-2"
status = "withdrawn"
severity = "major"
title = "T2"
detail = "D2"

[[finding]]
id = "F-3"
status = "open"
severity = "minor"
title = "T3"
detail = "D3"

# Findings are append-only `[[finding]]` tables, added by `review raise`.
# Empty here at creation — a fresh review is Active, awaiting the raiser.
"#
}

// === T2 — `review new` ======================================================

#[test]
fn new_creates_ledger_and_brief_byte_exact() {
    if skip_under_worker_marker("new_creates_ledger_and_brief_byte_exact") {
        return;
    }
    let dir = tmp();
    seed_slice(dir.path(), 1, &[]);

    let out = run(
        dir.path(),
        &["new", "--facet", "design", "--target", "SL-001"],
    );
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        norm(dir.path(), &stdout(&out)),
        "Created review 001: <ROOT>/.doctrine/review/001\n"
    );
    assert_eq!(
        stderr(&out),
        "doctrine: reservation reach degraded to local (no remote configured)\n"
    );
    assert_eq!(ledger(dir.path(), 1), fresh_ledger());
    assert_eq!(
        fs::read_to_string(dir.path().join(".doctrine/review/001/review-001.md")).unwrap(),
        fresh_brief()
    );
    let link = fs::read_link(
        dir.path()
            .join(".doctrine/review/001-design-review-of-sl-001"),
    )
    .expect("symlink alias");
    assert_eq!(link, Path::new("001"));
}

#[test]
fn new_with_phase_and_labels_omits_blank_line_before_findings_comment() {
    if skip_under_worker_marker(
        "new_with_phase_and_labels_omits_blank_line_before_findings_comment",
    ) {
        return;
    }
    let dir = tmp();
    seed_slice(dir.path(), 1, &[]);

    let out = run(
        dir.path(),
        &[
            "new",
            "--facet",
            "design",
            "--target",
            "SL-001",
            "--phase",
            "PHASE-01",
            "--title",
            "My T",
            "--raiser",
            "codex",
            "--responder",
            "claude",
        ],
    );
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(ledger(dir.path(), 1), fresh_ledger_with_phase_and_labels());
    assert_eq!(
        fs::read_to_string(dir.path().join(".doctrine/review/001/review-001.md")).unwrap(),
        fresh_brief()
    );
}

#[test]
fn new_allocates_next_available_id() {
    if skip_under_worker_marker("new_allocates_next_available_id") {
        return;
    }
    let dir = tmp();
    seed_slice(dir.path(), 1, &[]);
    run(
        dir.path(),
        &["new", "--facet", "design", "--target", "SL-001"],
    );

    let out = run(
        dir.path(),
        &["new", "--facet", "design", "--target", "SL-001"],
    );
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        norm(dir.path(), &stdout(&out)),
        "Created review 002: <ROOT>/.doctrine/review/002\n"
    );
    assert!(
        dir.path()
            .join(".doctrine/review/002/review-002.toml")
            .is_file()
    );
}

#[test]
fn new_refuses_dangling_target_creates_nothing() {
    if skip_under_worker_marker("new_refuses_dangling_target_creates_nothing") {
        return;
    }
    let dir = tmp();
    fs::create_dir_all(dir.path().join(".doctrine")).unwrap();

    let out = run(
        dir.path(),
        &["new", "--facet", "design", "--target", "SL-001"],
    );
    assert!(!out.status.success());
    assert_eq!(stdout(&out), "");
    assert_eq!(stderr(&out), "Error: target not found: SL-001\n");
    assert!(
        !dir.path().join(".doctrine/review").exists(),
        "the dangling-ref check runs BEFORE reservation — no review dir at all"
    );
}

// === T3 — the write chain on a seeded ledger ================================

#[test]
fn write_chain_pins_ledger_after_each_step() {
    if skip_under_worker_marker("write_chain_pins_ledger_after_each_step") {
        return;
    }
    let dir = tmp();
    seed_review(dir.path(), 1, fresh_ledger(), fresh_brief());

    // S3 — raise F-1.
    let out = run(
        dir.path(),
        &[
            "raise",
            "1",
            "--severity",
            "blocker",
            "--title",
            "T1",
            "--detail",
            "D1",
        ],
    );
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "Raised F-1 on RV-001\n");
    assert_eq!(ledger(dir.path(), 1), chain_step1_raise_f1());

    // raise F-2 (sets up the withdraw-later target).
    let out = run(
        dir.path(),
        &[
            "raise",
            "1",
            "--severity",
            "major",
            "--title",
            "T2",
            "--detail",
            "D2",
        ],
    );
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "Raised F-2 on RV-001\n");
    assert_eq!(ledger(dir.path(), 1), chain_step2_raise_f2());

    // S4 — dispose F-1.
    let out = run(
        dir.path(),
        &[
            "dispose",
            "1",
            "--finding",
            "F-1",
            "--disposition",
            "fixed",
            "--response",
            "R1",
        ],
    );
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "Disposed F-1 on RV-001 (answered)\n");
    assert_eq!(ledger(dir.path(), 1), chain_step3_dispose_f1());

    // S5 — contest F-1 (the note is baton-only; ledger proves it never lands there).
    let out = run(
        dir.path(),
        &["contest", "1", "--finding", "F-1", "--note", "not really"],
    );
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "Contested F-1 on RV-001 (contested)\n");
    assert_eq!(ledger(dir.path(), 1), chain_step4_contest_f1());

    // dispose F-1 again (contested → answered), byte-identical to the first dispose.
    let out = run(
        dir.path(),
        &[
            "dispose",
            "1",
            "--finding",
            "F-1",
            "--disposition",
            "fixed",
            "--response",
            "R1",
        ],
    );
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "Disposed F-1 on RV-001 (answered)\n");
    assert_eq!(ledger(dir.path(), 1), chain_step3_dispose_f1());

    // S6 — verify F-1.
    let out = run(
        dir.path(),
        &["verify", "1", "--finding", "F-1", "--note", "ok"],
    );
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "Verified F-1 on RV-001 (verified)\n");
    assert_eq!(ledger(dir.path(), 1), chain_step6_verify_f1());

    // S7 — withdraw F-2.
    let out = run(dir.path(), &["withdraw", "1", "--finding", "F-2"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "Withdrew F-2 on RV-001 (withdrawn)\n");
    assert_eq!(ledger(dir.path(), 1), chain_step7_withdraw_f2());

    // S8 — conclude, then again (idempotent).
    let out = run(dir.path(), &["conclude", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "Concluded the pass on RV-001\n");
    assert_eq!(ledger(dir.path(), 1), chain_step8_conclude());

    let out = run(dir.path(), &["conclude", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "Concluded the pass on RV-001 (already concluded)\n"
    );
    assert_eq!(ledger(dir.path(), 1), chain_step8_conclude());

    // S10 — status over the full chain: 9 turns written above, all terminal, concluded.
    let out = run(dir.path(), &["status", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "RV-001 — done · await=none · findings 2 · rounds 9 · concluded\n"
    );

    // S9 — raise on a concluded ledger still succeeds; concluded stays true
    // (D2 flips this later — today's behaviour, pinned as-is).
    let out = run(
        dir.path(),
        &[
            "raise",
            "1",
            "--severity",
            "minor",
            "--title",
            "T3",
            "--detail",
            "D3",
        ],
    );
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "Raised F-3 on RV-001\n");
    assert_eq!(ledger(dir.path(), 1), chain_step10_raise_on_concluded());
}

// === T4 — role refusals (R1-R8) =============================================

#[test]
fn role_refusals_pin_ledger_unchanged() {
    if skip_under_worker_marker("role_refusals_pin_ledger_unchanged") {
        return;
    }
    let dir = tmp();
    seed_one_finding(dir.path(), "open");
    let before = ledger(dir.path(), 1);

    // R1
    let out = run(
        dir.path(),
        &[
            "raise",
            "1",
            "--severity",
            "blocker",
            "--title",
            "T",
            "--detail",
            "D",
            "--as",
            "responder",
        ],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: `raise` is the raiser's verb; --as responder cannot assert it\n"
    );

    // R2
    let out = run(
        dir.path(),
        &[
            "dispose",
            "1",
            "--finding",
            "F-1",
            "--disposition",
            "d",
            "--response",
            "r",
            "--as",
            "raiser",
        ],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: `dispose` is the responder's verb; --as raiser cannot assert it\n"
    );

    // R3
    let out = run(
        dir.path(),
        &["verify", "1", "--finding", "F-1", "--as", "responder"],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: `verify` is the raiser's verb; --as responder cannot assert it\n"
    );

    // R4
    let out = run(
        dir.path(),
        &["contest", "1", "--finding", "F-1", "--as", "responder"],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: `contest` is the raiser's verb; --as responder cannot assert it\n"
    );

    // R5
    let out = run(
        dir.path(),
        &["withdraw", "1", "--finding", "F-1", "--as", "responder"],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: `withdraw` is the raiser's verb; --as responder cannot assert it\n"
    );

    // R6
    let out = run(dir.path(), &["conclude", "1", "--as", "responder"]);
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: `conclude` is the raiser's verb; --as responder cannot assert it\n"
    );

    // R7
    let out = run(
        dir.path(),
        &[
            "raise",
            "1",
            "--severity",
            "blocker",
            "--title",
            "T",
            "--detail",
            "D",
            "--as",
            "bogus",
        ],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: unknown --as role `bogus` (known: raiser, responder)\n"
    );

    assert_eq!(ledger(dir.path(), 1), before, "no role refusal ever writes");
}

#[test]
fn role_refusal_treats_ledgers_declared_raiser_label_as_unknown() {
    if skip_under_worker_marker("role_refusal_treats_ledgers_declared_raiser_label_as_unknown") {
        return;
    }
    // R8: a ledger whose `raiser = "codex"` still refuses `--as codex` today —
    // `parse_role` only ever knows raiser/responder (D8 teaches it declared
    // labels later). Pinned as today's behaviour.
    let dir = tmp();
    let toml = "id    = 1\nslug  = \"t\"\ntitle = \"T\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"codex\"\nresponder = \"claude\"\n\n[target]\nref   = \"SL-001\"\n\n[[finding]]\nid = \"F-1\"\nstatus = \"open\"\nseverity = \"blocker\"\ntitle = \"T1\"\ndetail = \"D1\"\n";
    seed_review(dir.path(), 1, toml, "# brief\n");
    let before = ledger(dir.path(), 1);

    let out = run(
        dir.path(),
        &[
            "raise",
            "1",
            "--severity",
            "blocker",
            "--title",
            "T",
            "--detail",
            "D",
            "--as",
            "codex",
        ],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: unknown --as role `codex` (known: raiser, responder)\n"
    );
    assert_eq!(ledger(dir.path(), 1), before);
}

// === T5 — state refusals (T1-T9) + X3 =======================================

#[test]
fn dispose_state_refusals_pin_ledger_unchanged() {
    if skip_under_worker_marker("dispose_state_refusals_pin_ledger_unchanged") {
        return;
    }
    // T1: dispose on `answered` — the refusal names `open` as required even
    // though `contested` is also legal (pinned as-is).
    let dir = tmp();
    seed_one_finding(dir.path(), "answered");
    let before = ledger(dir.path(), 1);
    let out = run(
        dir.path(),
        &[
            "dispose",
            "1",
            "--finding",
            "F-1",
            "--disposition",
            "d",
            "--response",
            "r",
        ],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: out of turn on F-1: current status answered != required open\n"
    );
    assert_eq!(ledger(dir.path(), 1), before);

    // T2: dispose on `verified`.
    let dir = tmp();
    seed_one_finding(dir.path(), "verified");
    let before = ledger(dir.path(), 1);
    let out = run(
        dir.path(),
        &[
            "dispose",
            "1",
            "--finding",
            "F-1",
            "--disposition",
            "d",
            "--response",
            "r",
        ],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: out of turn on F-1: current status verified != required open\n"
    );
    assert_eq!(ledger(dir.path(), 1), before);

    // T3: dispose on `withdrawn`.
    let dir = tmp();
    seed_one_finding(dir.path(), "withdrawn");
    let before = ledger(dir.path(), 1);
    let out = run(
        dir.path(),
        &[
            "dispose",
            "1",
            "--finding",
            "F-1",
            "--disposition",
            "d",
            "--response",
            "r",
        ],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: out of turn on F-1: current status withdrawn != required open\n"
    );
    assert_eq!(ledger(dir.path(), 1), before);
}

#[test]
fn verify_and_contest_state_refusals_pin_ledger_unchanged() {
    if skip_under_worker_marker("verify_and_contest_state_refusals_pin_ledger_unchanged") {
        return;
    }
    // T4: verify on `open`.
    let dir = tmp();
    seed_one_finding(dir.path(), "open");
    let before = ledger(dir.path(), 1);
    let out = run(dir.path(), &["verify", "1", "--finding", "F-1"]);
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: out of turn on F-1: current status open != required answered\n"
    );
    assert_eq!(ledger(dir.path(), 1), before);

    // T5: contest on `open`.
    let dir = tmp();
    seed_one_finding(dir.path(), "open");
    let before = ledger(dir.path(), 1);
    let out = run(dir.path(), &["contest", "1", "--finding", "F-1"]);
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: out of turn on F-1: current status open != required answered\n"
    );
    assert_eq!(ledger(dir.path(), 1), before);

    // T6: contest on `verified`.
    let dir = tmp();
    seed_one_finding(dir.path(), "verified");
    let before = ledger(dir.path(), 1);
    let out = run(dir.path(), &["contest", "1", "--finding", "F-1"]);
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: out of turn on F-1: current status verified != required answered\n"
    );
    assert_eq!(ledger(dir.path(), 1), before);
}

#[test]
fn withdraw_state_refusals_pin_ledger_unchanged() {
    if skip_under_worker_marker("withdraw_state_refusals_pin_ledger_unchanged") {
        return;
    }
    // T7: withdraw on `verified`.
    let dir = tmp();
    seed_one_finding(dir.path(), "verified");
    let before = ledger(dir.path(), 1);
    let out = run(dir.path(), &["withdraw", "1", "--finding", "F-1"]);
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: out of turn on F-1: current status verified != required open\n"
    );
    assert_eq!(ledger(dir.path(), 1), before);

    // T8: withdraw on `contested`.
    let dir = tmp();
    seed_one_finding(dir.path(), "contested");
    let before = ledger(dir.path(), 1);
    let out = run(dir.path(), &["withdraw", "1", "--finding", "F-1"]);
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: out of turn on F-1: current status contested != required open\n"
    );
    assert_eq!(ledger(dir.path(), 1), before);
}

#[test]
fn unknown_finding_and_bad_reference_refused() {
    if skip_under_worker_marker("unknown_finding_and_bad_reference_refused") {
        return;
    }
    // T9: unknown finding id.
    let dir = tmp();
    seed_one_finding(dir.path(), "open");
    let before = ledger(dir.path(), 1);
    let out = run(
        dir.path(),
        &[
            "dispose",
            "1",
            "--finding",
            "F-9",
            "--disposition",
            "d",
            "--response",
            "r",
        ],
    );
    assert!(!out.status.success());
    assert_eq!(stderr(&out), "Error: no finding `F-9` in the ledger\n");
    assert_eq!(ledger(dir.path(), 1), before);

    // X3: a garbage review reference.
    let dir2 = tmp();
    seed_one_finding(dir2.path(), "open");
    let out = run(
        dir2.path(),
        &[
            "raise",
            "RV-xyz",
            "--severity",
            "blocker",
            "--title",
            "T",
            "--detail",
            "D",
        ],
    );
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: not a review reference: `RV-xyz` (expected `RV-007` or `7`)\n\nCaused by:\n    invalid digit found in string\n"
    );
}

// === T8 — lock contention + unlock ==========================================

#[test]
fn lock_contention_refuses_write_and_status() {
    if skip_under_worker_marker("lock_contention_refuses_write_and_status") {
        return;
    }
    // T10: a seeded (stale-looking but present) lock refuses every write verb
    // AND `status` (which also acquires the lock to serialize its baton write).
    let dir = tmp();
    seed_one_finding(dir.path(), "open");
    seed_lock(
        dir.path(),
        1,
        "pid = 42\nacquired = \"2026-01-01T00:00:00Z\"\n",
    );
    let before = ledger(dir.path(), 1);

    let expected = "Error: RV-001: busy (another `review` invocation holds the lock); re-run (a stale lock from a hard kill clears with `review unlock`)\n";

    let out = run(
        dir.path(),
        &[
            "raise",
            "1",
            "--severity",
            "blocker",
            "--title",
            "T",
            "--detail",
            "D",
        ],
    );
    assert!(!out.status.success());
    assert_eq!(stderr(&out), expected);

    let out = run(dir.path(), &["status", "1"]);
    assert!(!out.status.success());
    assert_eq!(stderr(&out), expected);

    assert_eq!(
        ledger(dir.path(), 1),
        before,
        "lock contention never writes"
    );
}

#[test]
fn unlock_pins_stale_lock_removal_and_no_lock_message() {
    if skip_under_worker_marker("unlock_pins_stale_lock_removal_and_no_lock_message") {
        return;
    }
    // S13: no lock present.
    let dir = tmp();
    seed_one_finding(dir.path(), "open");
    let out = run(dir.path(), &["unlock", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "RV-001 is not locked\n");

    // S14: a seeded lock is printed then removed.
    let dir2 = tmp();
    seed_one_finding(dir2.path(), "open");
    seed_lock(
        dir2.path(),
        1,
        "pid = 42\nacquired = \"2026-01-01T00:00:00Z\"\n",
    );
    let out = run(dir2.path(), &["unlock", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "Removing stale lock for RV-001:\n  pid = 42\n  acquired = \"2026-01-01T00:00:00Z\"\n"
    );
    assert!(
        !dir2.path().join(".doctrine/state/review/001/lock").exists(),
        "unlock removes the lock file"
    );
}

// === T6 — reads on seeded fixtures ===========================================

#[test]
fn list_table_json_and_target_filter() {
    let dir = tmp();
    seed_review(
        dir.path(),
        1,
        "id    = 1\nslug  = \"t\"\ntitle = \"T1\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-001\"\n\n[[finding]]\nid = \"F-1\"\nstatus = \"open\"\nseverity = \"blocker\"\ntitle = \"T1\"\ndetail = \"D1\"\n",
        "# brief\n",
    );
    seed_review(
        dir.path(),
        2,
        "id    = 2\nslug  = \"u\"\ntitle = \"T2\"\n\n[review]\nfacet     = \"code-review\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-002\"\n",
        "# brief2\n",
    );

    let out = run(dir.path(), &["list"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "id     │ status                   │ facet       │ target │ title\n\
         RV-001 │ active (await responder) │ design      │ SL-001 │ T1\n\
         RV-002 │ done (await none)        │ code-review │ SL-002 │ T2\n"
    );

    let out = run(dir.path(), &["list", "--json"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "{\n  \"kind\": \"review\",\n  \"rows\": [\n    {\n      \"awaiting\": \"responder\",\n      \"facet\": \"design\",\n      \"id\": \"RV-001\",\n      \"status\": \"active\",\n      \"tags\": [],\n      \"target\": \"SL-001\",\n      \"title\": \"T1\"\n    },\n    {\n      \"awaiting\": \"none\",\n      \"facet\": \"code-review\",\n      \"id\": \"RV-002\",\n      \"status\": \"done\",\n      \"tags\": [],\n      \"target\": \"SL-002\",\n      \"title\": \"T2\"\n    }\n  ]\n}"
    );

    let out = run(dir.path(), &["list", "--target", "SL-002"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "id     │ status            │ facet       │ target │ title\n\
         RV-002 │ done (await none) │ code-review │ SL-002 │ T2\n"
    );
}

#[test]
fn show_with_findings_and_phase_table_and_json() {
    let dir = tmp();
    seed_review(
        dir.path(),
        1,
        "id    = 1\nslug  = \"t\"\ntitle = \"T1\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-001\"\nphase = \"PHASE-01\"\n\n[[finding]]\nid = \"F-1\"\nstatus = \"open\"\nseverity = \"blocker\"\ntitle = \"Ti1\"\ndetail = \"De1\"\n\n[[finding]]\nid = \"F-2\"\nstatus = \"answered\"\nseverity = \"major\"\ntitle = \"Ti2\"\ndetail = \"De2\"\ndisposition = \"fixed\"\nresponse = \"Resp2\"\n",
        "## Brief\nSome prose.\n",
    );

    let out = run(dir.path(), &["show", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "RV-001 — T1\n\
         design · active · await=responder\n\
         RV-001 ──reviews──▶ SL-001@PHASE-01\n\
         findings: 2 (raiser raiser · responder responder)\n\
         id  │ severity │ status   │ disposition │ title\n\
         F-1 │ blocker  │ open     │ —           │ Ti1\n\
         F-2 │ major    │ answered │ fixed       │ Ti2\n\
         \n\
         ## Brief\n\
         Some prose.\n"
    );

    let out = run(dir.path(), &["show", "1", "--json"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "{\n  \"body\": \"## Brief\\nSome prose.\\n\",\n  \"kind\": \"review\",\n  \"review\": {\n    \"awaiting\": \"responder\",\n    \"finding\": [\n      {\n        \"detail\": \"De1\",\n        \"disposition\": null,\n        \"id\": \"F-1\",\n        \"response\": null,\n        \"severity\": \"blocker\",\n        \"status\": \"open\",\n        \"title\": \"Ti1\"\n      },\n      {\n        \"detail\": \"De2\",\n        \"disposition\": \"fixed\",\n        \"id\": \"F-2\",\n        \"response\": \"Resp2\",\n        \"severity\": \"major\",\n        \"status\": \"answered\",\n        \"title\": \"Ti2\"\n      }\n    ],\n    \"id\": 1,\n    \"review\": {\n      \"concluded\": false,\n      \"facet\": \"design\",\n      \"raiser\": \"raiser\",\n      \"responder\": \"responder\"\n    },\n    \"slug\": \"t\",\n    \"status\": \"active\",\n    \"tags\": [],\n    \"target\": {\n      \"phase\": \"PHASE-01\",\n      \"ref\": \"SL-001\"\n    },\n    \"title\": \"T1\"\n  }\n}"
    );
}

#[test]
fn show_empty_ledger_plain_no_phase() {
    let dir = tmp();
    seed_review(
        dir.path(),
        1,
        "id    = 1\nslug  = \"t\"\ntitle = \"T1\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-001\"\n",
        "## Brief\nplain.\n",
    );

    let out = run(dir.path(), &["show", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "RV-001 — T1\n\
         design · done · await=none\n\
         RV-001 ──reviews──▶ SL-001\n\
         findings: 0 (raiser raiser · responder responder)\n\
         \n\
         ## Brief\n\
         plain.\n"
    );
}

#[test]
fn show_not_found_error() {
    let dir = tmp();
    seed_one_finding(dir.path(), "open");

    let out = run(dir.path(), &["show", "99"]);
    assert!(!out.status.success());
    assert_eq!(
        norm(dir.path(), &stderr(&out)),
        "Error: review 099 not found at <ROOT>/.doctrine/review/099/review-099.toml\n\nCaused by:\n    No such file or directory (os error 2)\n"
    );
}

#[test]
fn paths_variants() {
    let dir = tmp();
    seed_review(
        dir.path(),
        1,
        "id    = 1\nslug  = \"t\"\ntitle = \"T1\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-001\"\n",
        "# brief\n",
    );
    seed_review(
        dir.path(),
        2,
        "id    = 2\nslug  = \"u\"\ntitle = \"T2\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-002\"\n",
        "# brief2\n",
    );

    let out = run(dir.path(), &["paths", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        ".doctrine/review/001/review-001.toml\n.doctrine/review/001/review-001.md"
    );

    let out = run(dir.path(), &["paths", "1", "2"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        ".doctrine/review/001/review-001.toml\n.doctrine/review/001/review-001.md\n.doctrine/review/002/review-002.toml\n.doctrine/review/002/review-002.md"
    );

    let out = run(dir.path(), &["paths", "1", "--toml"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), ".doctrine/review/001/review-001.toml");

    let out = run(dir.path(), &["paths"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(stdout(&out), "");
}

#[test]
fn status_seeded_ledger_reports_rounds_zero() {
    let dir = tmp();
    seed_one_finding(dir.path(), "open");

    let out = run(dir.path(), &["status", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "RV-001 — active · await=responder · findings 1 · rounds 0\n"
    );
}

#[test]
fn vocab_defects_render_across_every_read_surface() {
    // A hand-edited finding with an out-of-vocabulary status/severity/
    // disposition (D15 flips this later — today's fail-open behaviour pinned
    // as-is): `show` renders it as `major`/`open`; `--json` passes the raw
    // strings through; `list`/`status` read it as active/await=responder.
    let dir = tmp();
    seed_review(
        dir.path(),
        1,
        "id    = 1\nslug  = \"t\"\ntitle = \"T1\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-001\"\n\n[[finding]]\nid = \"F-1\"\nstatus = \"zombie\"\nseverity = \"catastrophic\"\ntitle = \"Ti1\"\ndetail = \"De1\"\ndisposition = \"whatever\"\n",
        "# brief\n",
    );

    let out = run(dir.path(), &["show", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "RV-001 — T1\n\
         design · active · await=responder\n\
         RV-001 ──reviews──▶ SL-001\n\
         findings: 1 (raiser raiser · responder responder)\n\
         id  │ severity │ status │ disposition │ title\n\
         F-1 │ major    │ open   │ whatever    │ Ti1\n\
         \n\
         # brief\n"
    );

    let out = run(dir.path(), &["show", "1", "--json"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "{\n  \"body\": \"# brief\\n\",\n  \"kind\": \"review\",\n  \"review\": {\n    \"awaiting\": \"responder\",\n    \"finding\": [\n      {\n        \"detail\": \"De1\",\n        \"disposition\": \"whatever\",\n        \"id\": \"F-1\",\n        \"response\": null,\n        \"severity\": \"catastrophic\",\n        \"status\": \"zombie\",\n        \"title\": \"Ti1\"\n      }\n    ],\n    \"id\": 1,\n    \"review\": {\n      \"concluded\": false,\n      \"facet\": \"design\",\n      \"raiser\": \"raiser\",\n      \"responder\": \"responder\"\n    },\n    \"slug\": \"t\",\n    \"status\": \"active\",\n    \"tags\": [],\n    \"target\": {\n      \"phase\": null,\n      \"ref\": \"SL-001\"\n    },\n    \"title\": \"T1\"\n  }\n}"
    );

    let out = run(dir.path(), &["list"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "id     │ status                   │ facet  │ target │ title\n\
         RV-001 │ active (await responder) │ design │ SL-001 │ T1\n"
    );

    let out = run(dir.path(), &["status", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "RV-001 — active · await=responder · findings 1 · rounds 0\n"
    );
}

// === T7 — prime / status cache ===============================================

#[test]
fn prime_and_status_cache_current_then_stale() {
    let dir = tmp();
    seed_slice(dir.path(), 1, &["src/a.rs"]);
    seed_review(
        dir.path(),
        1,
        "id    = 1\nslug  = \"t\"\ntitle = \"T1\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-001\"\n",
        "# brief\n",
    );
    fs::create_dir_all(dir.path().join("src")).unwrap();
    fs::write(dir.path().join("src/a.rs"), "hello\n").unwrap();

    let out = run(dir.path(), &["prime", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "RV-001 primed — 1 tracked path(s) from the target slice's selectors\n"
    );

    let out = run(dir.path(), &["status", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "RV-001 — done · await=none · findings 0 · rounds 0\ncache: current\n"
    );

    fs::write(dir.path().join("src/a.rs"), "hello\nagain\n").unwrap();

    let out = run(dir.path(), &["status", "1"]);
    assert!(out.status.success(), "stderr: {}", stderr(&out));
    assert_eq!(
        stdout(&out),
        "RV-001 — done · await=none · findings 0 · rounds 0\ncache: stale (src/a.rs)\n"
    );
}

#[test]
fn prime_refuses_non_slice_target() {
    // X4: the review's `[target].ref` is an ADR, not a slice — no selectors to
    // prime from.
    let dir = tmp();
    seed_adr(dir.path(), 1);
    seed_review(
        dir.path(),
        1,
        "id    = 1\nslug  = \"t\"\ntitle = \"T1\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"ADR-001\"\n",
        "# brief\n",
    );

    let out = run(dir.path(), &["prime", "1"]);
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: review prime needs a slice target: RV-001 targets `ADR-001`, which is not a slice reference (no selectors to prime from)\n\nCaused by:\n    0: not a slice reference: `ADR-001` (expected `SL-007` or `7`)\n    1: invalid digit found in string\n"
    );
}

#[test]
fn prime_refuses_zero_selector_slice() {
    // X5: the target slice declares no `[[selector]]` rows at all.
    let dir = tmp();
    seed_slice(dir.path(), 1, &[]);
    seed_review(
        dir.path(),
        1,
        "id    = 1\nslug  = \"t\"\ntitle = \"T1\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-001\"\n",
        "# brief\n",
    );

    let out = run(dir.path(), &["prime", "1"]);
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: slice SL-001 declares no selectors — review prime has no path-set to track (add `[[selector]]` entries to the slice)\n"
    );
}

#[test]
fn prime_refuses_directory_selector() {
    // X7 (ISS-059, D11 changes this later): a literal selector naming a
    // directory is passed straight through to hashing and fails there.
    // Deterministic and path-free, so it is pinned rather than carved out.
    let dir = tmp();
    seed_slice(dir.path(), 1, &["src"]);
    seed_review(
        dir.path(),
        1,
        "id    = 1\nslug  = \"t\"\ntitle = \"T1\"\n\n[review]\nfacet     = \"design\"\nraiser    = \"raiser\"\nresponder = \"responder\"\n\n[target]\nref   = \"SL-001\"\n",
        "# brief\n",
    );
    fs::create_dir_all(dir.path().join("src")).unwrap();
    fs::write(dir.path().join("src/a.rs"), "hi\n").unwrap();

    let out = run(dir.path(), &["prime", "1"]);
    assert!(!out.status.success());
    assert_eq!(
        stderr(&out),
        "Error: hash the slice selector fileset\n\nCaused by:\n    Is a directory (os error 21)\n"
    );
}

// === X6 — clap value refusals =================================================

#[test]
fn clap_value_refusals_pin_full_stderr() {
    // clap's own value_parser refusals fire before the command ever dispatches
    // (no root/fixture needed at all — the parse fails first).
    let dir = tmp();

    let out = run(
        dir.path(),
        &[
            "raise",
            "1",
            "--severity",
            "bogus",
            "--title",
            "T",
            "--detail",
            "D",
        ],
    );
    assert_eq!(out.status.code(), Some(2));
    assert_eq!(stdout(&out), "");
    assert_eq!(
        stderr(&out),
        "error: invalid value 'bogus' for '--severity <SEVERITY>': unknown severity `bogus` (known: blocker, major, minor, nit)\n\nFor more information, try '--help'.\n"
    );

    let out = run(
        dir.path(),
        &["new", "--facet", "bogus", "--target", "SL-001"],
    );
    assert_eq!(out.status.code(), Some(2));
    assert_eq!(stdout(&out), "");
    assert_eq!(
        stderr(&out),
        "error: invalid value 'bogus' for '--facet <FACET>': unknown facet `bogus` (known: scope, design, plan, phase-plan, implementation, code-review, reconciliation)\n\nFor more information, try '--help'.\n"
    );
}
