//! The golden net — VT-3 (determinism+, F24) and VT-4 (REQ-077 full).
//!
//! Two hand-rolled property harnesses, ZERO dependencies (REQ-079): the crate
//! forbids a `[dependencies]` section, so there is no `proptest`/`quickcheck` —
//! permutation is an explicit loop and the SCC/topo oracle is an independent
//! reference implementation written here in test code.
//!
//! - **Permutation determinism (VT-3 / F24):** the same logical graph built from
//!   every permutation of its edge-insertion order yields byte-identical
//!   `order_key`, `Channel`, `Provenance`, and `Explanation`. No incidental
//!   insertion-order or map-iteration order leaks into any output.
//! - **Build-twice determinism (VT-4 / REQ-077):** building the same inputs twice
//!   produces identical `order_key` + `Provenance` + contributor traces.
//! - **Naive-oracle SCC/topo (VT-3 / R1 / REQ-076):** an independent reachability-
//!   closure SCC finder and a naive topo witness cross-check the engine — the
//!   diagnosed cycle set agrees with the oracle's SCCs, and `ordered()` never
//!   emits a false topological order (a successor never precedes its predecessor
//!   on an acyclic view; a cyclic Reject view degrades rather than lying).
//!
//! Black-box throughout: opaque builder ids, structural vocabulary only.

use std::collections::{BTreeMap, BTreeSet};

use cordage::{
    Arity, Channel, ChannelSpec, ChannelValue, Combinator, CyclePolicy, Direction, EdgeAttrs,
    Explanation, Graph, GraphBuilder, NodeId, OrderKey, OrderLayer, OrderSpec, OverlayConfig,
    Provenance,
};

// ── shared fixture vocabulary ─────────────────────────────────────────────────

fn reject() -> OverlayConfig {
    OverlayConfig::new(CyclePolicy::Reject, Arity::Unbounded)
}

fn evict() -> OverlayConfig {
    OverlayConfig::new(CyclePolicy::Evict, Arity::Unbounded)
}

/// A single authored edge, described by node *ordinals* (indices into the minted
/// node vector) so a fixture is order-independent data the permutation loop can
/// shuffle.
#[derive(Debug, Clone, Copy)]
struct EdgeSpec {
    src: usize,
    dst: usize,
    rank: i32,
    age: u64,
}

const fn e(src: usize, dst: usize, rank: i32, age: u64) -> EdgeSpec {
    EdgeSpec {
        src,
        dst,
        rank,
        age,
    }
}

/// Build a graph: `node_count` opaque nodes, one overlay with `config`, the given
/// edges inserted **in `order`** (a permutation of `0..edges.len()`), and an
/// order spec over the overlay in `Direction::Along`. Returns the graph plus the
/// minted node ids (mint order is fixed, so node identity is permutation-stable).
fn build_in_order(
    node_count: usize,
    config: OverlayConfig,
    edges: &[EdgeSpec],
    order: &[usize],
) -> (Graph, Vec<NodeId>) {
    let mut b = GraphBuilder::new();
    let ov = b.overlay(config);
    let nodes: Vec<NodeId> = (0..node_count).map(|_| b.node()).collect();
    for &i in order {
        let spec = edges.get(i).expect("permutation index in range");
        let src = *nodes.get(spec.src).expect("src ordinal in range");
        let dst = *nodes.get(spec.dst).expect("dst ordinal in range");
        b.edge(ov, src, dst, EdgeAttrs::new(spec.rank, spec.age));
    }
    b.order_spec(OrderSpec::new(vec![OrderLayer::new(ov, Direction::Along)]));
    let g = b.build().expect("valid build");
    (g, nodes)
}

/// All permutations of `0..n`, generated by Heap's algorithm — a hand-rolled
/// permutation set (no `itertools`, no dep). `n!` grows fast: keep fixtures small
/// (n ≤ 5 → ≤ 120 perms).
fn permutations(n: usize) -> Vec<Vec<usize>> {
    let mut a: Vec<usize> = (0..n).collect();
    let mut out = Vec::new();
    let mut c = vec![0usize; n];
    out.push(a.clone());
    let mut i = 0;
    while i < n {
        if *c.get(i).expect("counter index") < i {
            if i % 2 == 0 {
                a.swap(0, i);
            } else {
                let ci = *c.get(i).expect("counter index");
                a.swap(ci, i);
            }
            out.push(a.clone());
            let ci = c.get_mut(i).expect("counter index");
            *ci += 1;
            i = 0;
        } else {
            *c.get_mut(i).expect("counter index") = 0;
            i += 1;
        }
    }
    out
}

#[test]
fn permutations_are_exhaustive_and_distinct() {
    // Guard the harness itself: Heap's algorithm yields exactly n! distinct perms.
    let perms = permutations(4);
    assert_eq!(perms.len(), 24);
    let distinct: BTreeSet<Vec<usize>> = perms.iter().cloned().collect();
    assert_eq!(distinct.len(), 24);
    // n = 1 and n = 0 degenerate cleanly.
    assert_eq!(permutations(1), vec![vec![0]]);
    assert_eq!(permutations(0), vec![Vec::<usize>::new()]);
}

// ── derived snapshots for byte-identical comparison ───────────────────────────

/// Every node's composed-order key, as an order-independent map. `Graph::order_key`
/// + `OrderKey` derive `PartialEq`/`Eq`, so this `BTreeMap` compares byte-exact.
fn order_keys(g: &Graph, nodes: &[NodeId]) -> BTreeMap<NodeId, OrderKey> {
    nodes
        .iter()
        .filter_map(|&n| g.order_key(n).map(|k| (n, k)))
        .collect()
}

/// Every node's explanation, keyed by node — `Explanation` derives `PartialEq`.
fn explanations(g: &Graph, nodes: &[NodeId]) -> BTreeMap<NodeId, Explanation> {
    nodes.iter().map(|&n| (n, g.explain(n))).collect()
}

// ── VT-3: edge-insertion-permutation determinism (F24) ────────────────────────

/// Assert that a fixture is byte-identical across every edge-insertion permutation:
/// `order_key` (all nodes), `Provenance`, `Explanation` (all nodes), and a fixed
/// `Channel`. The first permutation is the reference; every other must match it.
fn assert_permutation_invariant(node_count: usize, config: OverlayConfig, edges: &[EdgeSpec]) {
    let perms = permutations(edges.len());
    let mut reference: Option<(
        BTreeMap<NodeId, OrderKey>,
        Provenance,
        BTreeMap<NodeId, Explanation>,
        Channel,
    )> = None;

    for order in &perms {
        let (g, nodes) = build_in_order(node_count, config, edges, order);
        let keys = order_keys(&g, &nodes);
        let prov = g.provenance().clone();
        let exps = explanations(&g, &nodes);
        // A fixed channel: Any/Against over the overlay, seeding node 0 true.
        let spec = ChannelSpec::new(cordage_overlay(), Combinator::Any, Direction::Against);
        let mut seeds: BTreeMap<NodeId, ChannelValue> = BTreeMap::new();
        if let Some(&first) = nodes.first() {
            seeds.insert(first, ChannelValue::Flag(true));
        }
        let channel = g.evaluate(spec, &seeds);

        match &reference {
            None => reference = Some((keys, prov, exps, channel)),
            Some((rk, rp, re, rc)) => {
                assert_eq!(&keys, rk, "order_key drifted across edge permutation");
                assert_eq!(&prov, rp, "provenance drifted across edge permutation");
                assert_eq!(&exps, re, "explanation drifted across edge permutation");
                assert_eq!(&channel, rc, "channel drifted across edge permutation");
            }
        }
    }
}

/// The single overlay in every fixture here is the first allocated → ordinal 0.
/// There is no public `OverlayId` constructor, so recover it from a throwaway
/// builder (mint order is fixed).
fn cordage_overlay() -> cordage::OverlayId {
    let mut b = GraphBuilder::new();
    b.overlay(reject())
}

#[test]
fn permutation_determinism_on_a_clean_dag() {
    // A diamond + tail: 0→1, 0→2, 1→3, 2→3, 3→4 — five edges, 120 permutations.
    let edges = [
        e(0, 1, 0, 0),
        e(0, 2, 0, 0),
        e(1, 3, 0, 0),
        e(2, 3, 0, 0),
        e(3, 4, 0, 0),
    ];
    assert_permutation_invariant(5, reject(), &edges);
}

#[test]
fn permutation_determinism_on_an_evict_cycle() {
    // An Evict overlay with a 3-cycle plus a chord, varying rank/age so the
    // eviction selection is non-trivial: the evicted edge (and provenance) must be
    // identical regardless of insertion order.
    let edges = [
        e(0, 1, 2, 0),
        e(1, 2, 1, 0),
        e(2, 0, 0, 0), // weakest → evicted to break the cycle
        e(0, 2, 3, 1),
    ];
    assert_permutation_invariant(3, evict(), &edges);
}

#[test]
fn permutation_determinism_on_a_reject_cycle() {
    // A Reject overlay with a 2-cycle plus a tail: the diagnosed cycle, the
    // degraded order, and explain must all be permutation-invariant.
    let edges = [e(0, 1, 0, 0), e(1, 0, 0, 0), e(0, 2, 0, 0)];
    assert_permutation_invariant(3, reject(), &edges);
}

// ── VT-4: build-twice determinism (REQ-077) ───────────────────────────────────

#[test]
fn build_twice_is_identical_order_provenance_and_contributor_traces() {
    // REQ-077: the SAME inputs built twice → identical order_key + Provenance +
    // contributor traces. Distinct Graph instances, compared by value.
    let edges = [e(0, 1, 2, 0), e(0, 2, 1, 0), e(1, 3, 0, 0), e(2, 3, 0, 0)];
    let identity: Vec<usize> = (0..edges.len()).collect();

    let (g1, n1) = build_in_order(4, reject(), &edges, &identity);
    let (g2, n2) = build_in_order(4, reject(), &edges, &identity);

    // order_key identical for every node.
    assert_eq!(order_keys(&g1, &n1), order_keys(&g2, &n2));
    // Provenance identical.
    assert_eq!(g1.provenance(), g2.provenance());

    // Contributor traces identical: a Max channel argmax-folds, recording the
    // contributing node behind each value.
    let spec = ChannelSpec::new(cordage_overlay(), Combinator::Max, Direction::Against);
    let mut seeds: BTreeMap<NodeId, ChannelValue> = BTreeMap::new();
    seeds.insert(n1[0], ChannelValue::Scalar(7));
    seeds.insert(n1[1], ChannelValue::Scalar(3));
    let c1 = g1.evaluate(spec, &seeds);
    let mut seeds2: BTreeMap<NodeId, ChannelValue> = BTreeMap::new();
    seeds2.insert(n2[0], ChannelValue::Scalar(7));
    seeds2.insert(n2[1], ChannelValue::Scalar(3));
    let c2 = g2.evaluate(spec, &seeds2);
    assert_eq!(
        c1, c2,
        "channel + contributor traces drifted across rebuild"
    );
    // The full Channel equality already covers contributors, but pin the trace
    // explicitly so the intent is legible.
    for &n in &n1 {
        assert_eq!(c1.contributors(n), c2.contributors(n));
    }
}

// ── VT-3 / R1: the naive independent SCC + topo oracle ────────────────────────
// Computed WITHOUT the production Tarjan/level machinery: SCCs by reachability
// closure (u,v same SCC iff u→*v and v→*u), topo by an edge-respect check. The
// oracle is the independent witness that the engine tells the truth on cycles.

/// Transitive successors of `start` over `adj` (reachability closure; excludes
/// `start` unless cyclically reachable). Naive BFS — no shared traversal code.
fn closure(adj: &BTreeMap<usize, BTreeSet<usize>>, start: usize) -> BTreeSet<usize> {
    let mut seen = BTreeSet::new();
    let mut frontier = vec![start];
    let mut first = true;
    while let Some(u) = frontier.pop() {
        if let Some(succ) = adj.get(&u) {
            for &w in succ {
                // Record reachability; re-entering `start` keeps it (cyclic).
                if seen.insert(w) || (w == start && first) {
                    frontier.push(w);
                }
            }
        }
        first = false;
    }
    seen
}

/// The non-trivial SCCs (size > 1, or a self-looped singleton) of `adj` over
/// `nodes`, by mutual-reachability closure. Independent of Tarjan.
fn oracle_sccs(
    adj: &BTreeMap<usize, BTreeSet<usize>>,
    nodes: &BTreeSet<usize>,
) -> Vec<BTreeSet<usize>> {
    let reach: BTreeMap<usize, BTreeSet<usize>> =
        nodes.iter().map(|&n| (n, closure(adj, n))).collect();
    let mut assigned: BTreeSet<usize> = BTreeSet::new();
    let mut comps: Vec<BTreeSet<usize>> = Vec::new();
    for &u in nodes {
        if assigned.contains(&u) {
            continue;
        }
        let mut comp: BTreeSet<usize> = BTreeSet::new();
        comp.insert(u);
        let u_reach = reach.get(&u).expect("closure present");
        for &v in nodes {
            if v == u {
                continue;
            }
            let v_reach = reach.get(&v).expect("closure present");
            if u_reach.contains(&v) && v_reach.contains(&u) {
                comp.insert(v);
            }
        }
        let self_loop = reach.get(&u).map(|r| r.contains(&u)).unwrap_or(false);
        if comp.len() > 1 || self_loop {
            for &m in &comp {
                assigned.insert(m);
            }
            comps.push(comp);
        }
    }
    comps
}

/// Build the ordinal adjacency + node set an oracle reads from an edge fixture.
fn fixture_adjacency(
    node_count: usize,
    edges: &[EdgeSpec],
) -> (BTreeMap<usize, BTreeSet<usize>>, BTreeSet<usize>) {
    let mut adj: BTreeMap<usize, BTreeSet<usize>> = BTreeMap::new();
    for spec in edges {
        adj.entry(spec.src).or_default().insert(spec.dst);
    }
    let nodes: BTreeSet<usize> = (0..node_count).collect();
    (adj, nodes)
}

#[test]
fn engine_diagnosed_cycles_agree_with_the_naive_oracle() {
    // A deterministic family of small Reject graphs (no rng — a fixed seed list).
    // For each, the engine's diagnosed cycle node-sets must equal the oracle's
    // non-trivial SCC node-sets, mapped back to ordinals.
    let fixtures: &[(usize, &[EdgeSpec])] = &[
        // acyclic diamond — no cycles either side.
        (
            4,
            &[e(0, 1, 0, 0), e(0, 2, 0, 0), e(1, 3, 0, 0), e(2, 3, 0, 0)],
        ),
        // one 2-cycle.
        (3, &[e(0, 1, 0, 0), e(1, 0, 0, 0), e(0, 2, 0, 0)]),
        // one 3-cycle with a tail.
        (
            4,
            &[e(0, 1, 0, 0), e(1, 2, 0, 0), e(2, 0, 0, 0), e(2, 3, 0, 0)],
        ),
        // two disjoint 2-cycles.
        (
            4,
            &[e(0, 1, 0, 0), e(1, 0, 0, 0), e(2, 3, 0, 0), e(3, 2, 0, 0)],
        ),
        // self-loop singleton.
        (2, &[e(0, 0, 0, 0), e(0, 1, 0, 0)]),
    ];

    for &(node_count, edges) in fixtures {
        let identity: Vec<usize> = (0..edges.len()).collect();
        let (g, nodes) = build_in_order(node_count, reject(), edges, &identity);

        // The engine's diagnosed cycle node-sets (as ordinal sets).
        let ordinal_of: BTreeMap<NodeId, usize> =
            nodes.iter().enumerate().map(|(i, &n)| (n, i)).collect();
        let mut engine: Vec<BTreeSet<usize>> = g
            .provenance()
            .cycles()
            .iter()
            .map(|c| {
                c.nodes()
                    .iter()
                    .map(|n| *ordinal_of.get(n).expect("known node"))
                    .collect()
            })
            .collect();
        engine.sort();

        let (adj, node_ords) = fixture_adjacency(node_count, edges);
        let mut oracle = oracle_sccs(&adj, &node_ords);
        oracle.sort();

        assert_eq!(
            engine, oracle,
            "engine cycle diagnostics disagree with the naive SCC oracle for {edges:?}"
        );
    }
}

#[test]
fn ordered_never_emits_a_false_topo_on_acyclic_views() {
    // The naive topo witness: on an acyclic overlay, every edge u→v must place u
    // strictly before v in `ordered()` (a longest-path level respects every edge).
    // REQ-076: the engine never lies about order on a clean DAG.
    let fixtures: &[(usize, &[EdgeSpec])] = &[
        (
            5,
            &[
                e(0, 1, 0, 0),
                e(0, 2, 0, 0),
                e(1, 3, 0, 0),
                e(2, 3, 0, 0),
                e(3, 4, 0, 0),
            ],
        ),
        (4, &[e(0, 1, 0, 0), e(1, 2, 0, 0), e(2, 3, 0, 0)]),
        (3, &[e(0, 2, 0, 0), e(1, 2, 0, 0)]),
    ];

    for &(node_count, edges) in fixtures {
        let identity: Vec<usize> = (0..edges.len()).collect();
        let (g, nodes) = build_in_order(node_count, reject(), edges, &identity);
        let position: BTreeMap<NodeId, usize> = g
            .ordered()
            .iter()
            .enumerate()
            .map(|(i, &n)| (n, i))
            .collect();

        for spec in edges {
            let src = nodes.get(spec.src).expect("src");
            let dst = nodes.get(spec.dst).expect("dst");
            let p_src = position.get(src).expect("src ordered");
            let p_dst = position.get(dst).expect("dst ordered");
            assert!(
                p_src < p_dst,
                "false topo: {src:?}@{p_src} not before {dst:?}@{p_dst} for edge {spec:?}",
            );
        }
    }
}

#[test]
fn ordered_degrades_rather_than_lying_on_a_reject_cycle() {
    // REQ-076: a cyclic Reject overlay must NOT yield a false topo order. The cycle
    // members carry no fabricated internal precedence (intra-SCC edges are excluded
    // from the order structure U), and the whole tainted region degrades. Crucially,
    // the SURVIVING acyclic edge 0→2 is still respected — taint changes the level
    // *tag*, not the longest-path depth, so 0 still precedes 2 in `ordered()` (F33:
    // the suffix is edge-respecting, never tainted→clean and never order-violating).
    let edges = [e(0, 1, 0, 0), e(1, 0, 0, 0), e(0, 2, 0, 0)];
    let identity: Vec<usize> = (0..edges.len()).collect();
    let (g, nodes) = build_in_order(3, reject(), &edges, &identity);

    // Oracle: {0,1} is the one SCC; 2 is acyclic downstream.
    let (adj, node_ords) = fixture_adjacency(3, &edges);
    let oracle = oracle_sccs(&adj, &node_ords);
    assert_eq!(oracle, vec![BTreeSet::from([0usize, 1usize])]);

    // Engine: the whole region degrades (cycle seed 0/1 + downstream 2) — degraded
    // taint is conservative, never a false clean order on a cyclic view.
    use cordage::Level;
    let level = |i: usize| g.order_key(nodes[i]).expect("order key").level();
    assert!(
        matches!(level(0), Level::Degraded(_)),
        "cycle member 0 degraded"
    );
    assert!(
        matches!(level(1), Level::Degraded(_)),
        "cycle member 1 degraded"
    );
    assert!(
        matches!(level(2), Level::Degraded(_)),
        "downstream 2 tainted"
    );

    // No false topo: the surviving edge 0→2 is honoured — 0 strictly precedes 2 in
    // the composed order (its longest-path depth is lower), and the SCC members do
    // not trail their own descendant.
    let ordered = g.ordered();
    let pos: BTreeMap<NodeId, usize> = ordered.iter().enumerate().map(|(i, &n)| (n, i)).collect();
    assert!(
        pos[&nodes[0]] < pos[&nodes[2]],
        "surviving edge 0→2 violated under degradation (false topo)",
    );
}
